### ISSUE TITLE
Subnested collection

### ISSUE THREAD

**Issue by m3doune** [wiese/jquery-sfPrototypeMan#2]
Hello, I have a form which contain a collection that contain another collection! How can I handle the inner collection with plugin!

Best regards!

**Comment by wiese** [comment]
You can either apply sfPrototypeMan to the entire DOM

``` javascript
jQuery().sfPrototypeMan();
```

or restrict the operation to an individual element

``` javascript
jQuery('#myitem').sfPrototypeMan();
```

See
https://github.com/wiese/jquery-sfPrototypeMan#usage

Does this answer the question?
